# Generated by Django 5.2.8 on 2025-12-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_artisttypeshow_show_artist_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'price_show',
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='artist_types',
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_price_type'),
        ),
        migrations.AddField(
            model_name='priceshow',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='show_links', to='catalogue.price'),
        ),
        migrations.AddField(
            model_name='priceshow',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_links', to='catalogue.show'),
        ),
        migrations.AddField(
            model_name='show',
            name='prices',
            field=models.ManyToManyField(related_name='shows', through='catalogue.PriceShow', to='catalogue.price'),
        ),
        migrations.AlterUniqueTogether(
            name='priceshow',
            unique_together={('show', 'price')},
        ),
    ]
