# Generated by Django 5.2.8 on 2025-12-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_priceshow_remove_show_artist_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='representation_reservations', to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='representation_reservations', to='catalogue.reservation')),
            ],
            options={
                'db_table': 'representation_reservation',
                'unique_together': {('representation', 'reservation')},
            },
        ),
        migrations.AddField(
            model_name='representation',
            name='reservations',
            field=models.ManyToManyField(related_name='representations', through='catalogue.RepresentationReservation', to='catalogue.reservation'),
        ),
    ]
