# Generated by Django 5.0.14 on 2026-05-10 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="ID du prix Stripe pour l'abonnement",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "api_limit_daily",
                    models.IntegerField(
                        default=100,
                        help_text="Nombre maximum d'appels API autorisés par jour",
                    ),
                ),
                (
                    "can_access_full_data",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, donne accès aux détails complets (artistes, prix, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau d'affiliation",
                "verbose_name_plural": "Niveaux d'affiliation",
            },
        ),
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Clé du paramètre"
                    ),
                ),
                ("value", models.TextField(verbose_name="Valeur")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètre de l'application",
                "verbose_name_plural": "Paramètres de l'application",
                "db_table": "app_settings",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=60)),
                ("lastname", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "artists",
            },
        ),
        migrations.CreateModel(
            name="ArtistType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "artist_type",
            },
        ),
        migrations.CreateModel(
            name="ArtistTypeShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "artist_type_show",
            },
        ),
        migrations.CreateModel(
            name="CriticRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("profession", models.CharField(max_length=100)),
                ("media_name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("motivation", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Refusé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Demande Critique",
                "verbose_name_plural": "Demandes Critiques",
                "db_table": "critic_requests",
            },
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(max_length=6)),
                ("locality", models.CharField(max_length=30)),
                ("locality_fr", models.CharField(max_length=30, null=True)),
                ("locality_en", models.CharField(max_length=30, null=True)),
                ("locality_nl", models.CharField(max_length=30, null=True)),
            ],
            options={
                "db_table": "localities",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=60, unique=True)),
                ("designation", models.CharField(max_length=60)),
                ("designation_fr", models.CharField(max_length=60, null=True)),
                ("designation_en", models.CharField(max_length=60, null=True)),
                ("designation_nl", models.CharField(max_length=60, null=True)),
                ("address", models.CharField(max_length=255)),
                ("address_fr", models.CharField(max_length=255, null=True)),
                ("address_en", models.CharField(max_length=255, null=True)),
                ("address_nl", models.CharField(max_length=255, null=True)),
                ("website", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                ("capacity", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si faux, la salle n'apparaîtra pas dans les listes publiques (utile pour modération).",
                    ),
                ),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_user", "Nouvel Utilisateur"),
                            ("producer_request", "Demande Producteur"),
                            ("critic_request", "Demande Critique"),
                            ("new_show", "Nouveau Spectacle"),
                            ("new_article", "Nouvel Article"),
                            ("info", "Information"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PressArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_nl", models.CharField(max_length=255, null=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Bref résumé de l'article pour l'affichage en liste.",
                        max_length=500,
                    ),
                ),
                (
                    "summary_fr",
                    models.TextField(
                        help_text="Bref résumé de l'article pour l'affichage en liste.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "summary_en",
                    models.TextField(
                        help_text="Bref résumé de l'article pour l'affichage en liste.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "summary_nl",
                    models.TextField(
                        help_text="Bref résumé de l'article pour l'affichage en liste.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("content", models.TextField(help_text="Corps complet de l'article.")),
                (
                    "content_fr",
                    models.TextField(
                        help_text="Corps complet de l'article.", null=True
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Corps complet de l'article.", null=True
                    ),
                ),
                (
                    "content_nl",
                    models.TextField(
                        help_text="Corps complet de l'article.", null=True
                    ),
                ),
                ("validated", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article de Presse",
                "verbose_name_plural": "Articles de Presse",
                "db_table": "press_articles",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("type_fr", models.CharField(max_length=30, null=True)),
                ("type_en", models.CharField(max_length=30, null=True)),
                ("type_nl", models.CharField(max_length=30, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=120)),
                ("description_fr", models.CharField(max_length=120, null=True)),
                ("description_en", models.CharField(max_length=120, null=True)),
                ("description_nl", models.CharField(max_length=120, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "prices",
            },
        ),
        migrations.CreateModel(
            name="ProducerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=30)),
                ("presentation", models.TextField(max_length=500)),
                ("motivation", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Refusé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Demande Producteur",
                "verbose_name_plural": "Demandes Producteurs",
                "db_table": "producer_requests",
            },
        ),
        migrations.CreateModel(
            name="Representation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule", models.DateTimeField()),
                ("available_seats", models.IntegerField(default=100)),
                ("total_seats", models.PositiveIntegerField(default=100)),
            ],
            options={
                "db_table": "representations",
            },
        ),
        migrations.CreateModel(
            name="RepresentationReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "representation_reservation",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "reservations",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("review_fr", models.TextField(null=True)),
                ("review_en", models.TextField(null=True)),
                ("review_nl", models.TextField(null=True)),
                ("stars", models.PositiveSmallIntegerField()),
                ("validated", models.BooleanField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=60, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("title_fr", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_nl", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(max_length=255, null=True)),
                ("description_fr", models.TextField(max_length=255, null=True)),
                ("description_en", models.TextField(max_length=255, null=True)),
                ("description_nl", models.TextField(max_length=255, null=True)),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
                ("duration", models.PositiveSmallIntegerField(null=True)),
                ("created_in", models.PositiveSmallIntegerField()),
                ("bookable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("published", "Publié")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "shows",
            },
        ),
        migrations.CreateModel(
            name="ShowPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_total", models.PositiveIntegerField(default=100)),
            ],
            options={
                "db_table": "show_prices",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Billet",
                "verbose_name_plural": "Billets",
                "db_table": "tickets",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=60)),
                ("type_fr", models.CharField(max_length=60, null=True)),
                ("type_en", models.CharField(max_length=60, null=True)),
                ("type_nl", models.CharField(max_length=60, null=True)),
            ],
            options={
                "db_table": "types",
            },
        ),
        migrations.CreateModel(
            name="UserMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("langue", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "user_meta",
            },
        ),
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.affiliatetier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affilié",
                "verbose_name_plural": "Affiliés",
            },
        ),
        migrations.CreateModel(
            name="AffiliatePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("status", models.CharField(default="succeeded", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="catalogue.affiliate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="catalogue.affiliate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log API",
                "verbose_name_plural": "Logs API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.UniqueConstraint(
                fields=("firstname", "lastname"), name="unique_firstname_lastname"
            ),
        ),
        migrations.AddField(
            model_name="artisttype",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="a_artistTypes",
                to="catalogue.artist",
            ),
        ),
        migrations.AddField(
            model_name="artisttypeshow",
            name="artist_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artistTypeShows",
                to="catalogue.artisttype",
            ),
        ),
        migrations.AddField(
            model_name="criticrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="critic_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="locality",
            constraint=models.UniqueConstraint(
                fields=("postal_code", "locality"), name="unique_postal_code_locality"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="locality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="locations",
                to="catalogue.locality",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pressarticle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="press_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producerrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="producer_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="representation",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="representations",
                to="catalogue.location",
            ),
        ),
        migrations.AddField(
            model_name="representationreservation",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="catalogue.price"
            ),
        ),
        migrations.AddField(
            model_name="representationreservation",
            name="representation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalogue.representation",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="representations",
            field=models.ManyToManyField(
                through="catalogue.RepresentationReservation",
                to="catalogue.representation",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="representationreservation",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="representation_reservations",
                to="catalogue.reservation",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="artist_types",
            field=models.ManyToManyField(
                related_name="shows",
                through="catalogue.ArtistTypeShow",
                to="catalogue.artisttype",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shows",
                to="catalogue.location",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="producer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_shows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reviews",
                to="catalogue.show",
            ),
        ),
        migrations.AddField(
            model_name="representation",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="representations",
                to="catalogue.show",
            ),
        ),
        migrations.AddField(
            model_name="pressarticle",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="press_articles",
                to="catalogue.show",
            ),
        ),
        migrations.AddField(
            model_name="artisttypeshow",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artistTypeShows",
                to="catalogue.show",
            ),
        ),
        migrations.AddField(
            model_name="showprice",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.price"
            ),
        ),
        migrations.AddField(
            model_name="showprice",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.show"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="prices",
            field=models.ManyToManyField(
                related_name="shows",
                through="catalogue.ShowPrice",
                to="catalogue.price",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="representation_reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="catalogue.representationreservation",
            ),
        ),
        migrations.AddField(
            model_name="artisttype",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="t_artistTypes",
                to="catalogue.type",
            ),
        ),
        migrations.AddField(
            model_name="usermeta",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("slug", "website"), name="unique_slug_website"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artisttypeshow",
            unique_together={("show", "artist_type")},
        ),
        migrations.AlterUniqueTogether(
            name="showprice",
            unique_together={("show", "price")},
        ),
        migrations.AddConstraint(
            model_name="show",
            constraint=models.UniqueConstraint(
                fields=("slug", "created_in"), name="unique_slug_created_in"
            ),
        ),
    ]
