# Generated by Django 5.0.14 on 2025-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_show_alter_locality_locality_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("slug", "website"), name="unique_slug_website"
            ),
        ),
    ]
