# Generated by Django 5.0.14 on 2026-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_representation_available_seats_reservation_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='created_in',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('firstname', 'lastname'), name='unique_firstname_lastname'),
        ),
    ]
