# Generated by Django 5.0.14 on 2026-01-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0023_alter_show_created_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="representation",
        ),
        migrations.CreateModel(
            name="RepresentationReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalogue.price",
                    ),
                ),
                (
                    "representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalogue.representation",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representation_reservations",
                        to="catalogue.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "representation_reservation",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="representations",
            field=models.ManyToManyField(
                through="catalogue.RepresentationReservation",
                to="catalogue.representation",
            ),
        ),
    ]
