# Generated by Django 5.0.14 on 2026-02-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0024_remove_reservation_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_type", models.CharField(default="standard", max_length=60)),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.price",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalogue.show"
                    ),
                ),
            ],
            options={
                "db_table": "show_prices",
                "unique_together": {("show", "price", "price_type")},
            },
        ),
        migrations.AddField(
            model_name="show",
            name="prices",
            field=models.ManyToManyField(
                related_name="shows",
                through="catalogue.ShowPrice",
                to="catalogue.price",
            ),
        ),
    ]
