# Generated by Django 5.0.14 on 2026-02-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0025_showprice_show_prices"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="showprice",
            unique_together={("show", "price")},
        ),
        migrations.RemoveField(
            model_name="showprice",
            name="price_type",
        ),
    ]
