# Generated by Django 5.0.14 on 2026-03-31 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_alter_showprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviews', to='catalogue.show'),
        ),
    ]
