# Generated by Django 6.0.3 on 2026-04-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_alter_review_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='designation_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='designation_fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='designation_nl',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='description_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='description_fr',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='description_nl',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='type_nl',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
