# Generated by Django 6.0.3 on 2026-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_location_designation_en_location_designation_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='description_fr',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='description_nl',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='type_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='type_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='type_nl',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
