# Generated by Django 6.0.3 on 2026-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_price_description_en_price_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='locality_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='locality_nl',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_fr'), name='unique_postal_code_locality-fr'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_en'), name='unique_postal_code_locality-en'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_nl'), name='unique_postal_code_locality-nl'),
        ),
    ]
