# Generated by Django 5.0.14 on 2026-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_remove_locality_unique_postal_code_locality_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_nl',
            field=models.TextField(null=True),
        ),
    ]
