# Generated by Django 5.0.14 on 2026-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_review_review_en_review_review_fr_review_review_nl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé du paramètre')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètre de l'application",
                'verbose_name_plural': "Paramètres de l'application",
                'db_table': 'app_settings',
            },
        ),
    ]
