# Generated by Django 6.0.3 on 2026-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_appsetting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_fr'), name='unique_postal_code_locality-fr'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_en'), name='unique_postal_code_locality-en'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_nl'), name='unique_postal_code_locality-nl'),
        ),
    ]
