# Generated by Django 5.0.14 on 2026-04-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_locality_unique_postal_code_locality_fr_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-fr',
        ),
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-en',
        ),
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-nl',
        ),
    ]
