# Generated by Django 5.0.14 on 2026-04-16 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_remove_locality_unique_postal_code_locality_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representation_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='catalogue.representationreservation')),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
                'db_table': 'tickets',
            },
        ),
    ]
