# Generated by Django 6.0.3 on 2026-04-16 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='representation',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='show',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('published', 'Publié')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_fr'), name='unique_postal_code_locality-fr'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_en'), name='unique_postal_code_locality-en'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('postal_code', 'locality_nl'), name='unique_postal_code_locality-nl'),
        ),
    ]
