# Generated by Django 6.0.3 on 2026-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_location_capacity_representation_total_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showprice',
            name='quantity_total',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
