# Generated by Django 6.0.3 on 2026-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_showprice_quantity_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
