# Generated by Django 5.0.14 on 2026-04-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_review_is_pinned'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-fr',
        ),
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-en',
        ),
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-nl',
        ),
        migrations.AddField(
            model_name='show',
            name='external_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
