# Generated by Django 5.0.14 on 2026-04-24 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0041_remove_locality_unique_postal_code_locality_fr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, help_text="ID du prix Stripe pour l'abonnement", max_length=100, null=True)),
                ('api_limit_daily', models.IntegerField(default=100, help_text="Nombre maximum d'appels API autorisés par jour")),
                ('can_access_full_data', models.BooleanField(default=False, help_text='Si activé, donne accès aux détails complets (artistes, prix, etc.)')),
            ],
            options={
                'verbose_name': "Niveau d'affiliation",
                'verbose_name_plural': "Niveaux d'affiliation",
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.affiliatetier')),
            ],
            options={
                'verbose_name': 'Affilié',
                'verbose_name_plural': 'Affiliés',
            },
        ),
    ]
