# Generated by Django 5.0.14 on 2026-05-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_notification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-fr',
        ),
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-en',
        ),
        migrations.RemoveConstraint(
            model_name='locality',
            name='unique_postal_code_locality-nl',
        ),
    ]
