# Generated by Django 5.0.14 on 2026-05-06 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_remove_locality_unique_postal_code_locality_fr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('profession', models.CharField(max_length=100)),
                ('media_name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critic_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande Critique',
                'verbose_name_plural': 'Demandes Critiques',
                'db_table': 'critic_requests',
            },
        ),
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text="Bref résumé de l'article pour l'affichage en liste.", max_length=500)),
                ('content', models.TextField(help_text="Corps complet de l'article.")),
                ('validated', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_articles', to='catalogue.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de Presse',
                'verbose_name_plural': 'Articles de Presse',
                'db_table': 'press_articles',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
