# Generated by Django 5.0.14 on 2026-05-07 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_criticrequest_pressarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_user', 'Nouvel Utilisateur'), ('producer_request', 'Demande Producteur'), ('critic_request', 'Demande Critique'), ('new_show', 'Nouveau Spectacle'), ('new_article', 'Nouvel Article'), ('info', 'Information')], max_length=50),
        ),
    ]
