# Generated by Django 5.0.14 on 2026-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_notification_user_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressarticle',
            name='content_en',
            field=models.TextField(help_text="Corps complet de l'article.", null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='content_fr',
            field=models.TextField(help_text="Corps complet de l'article.", null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='content_nl',
            field=models.TextField(help_text="Corps complet de l'article.", null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='summary_en',
            field=models.TextField(help_text="Bref résumé de l'article pour l'affichage en liste.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='summary_fr',
            field=models.TextField(help_text="Bref résumé de l'article pour l'affichage en liste.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='summary_nl',
            field=models.TextField(help_text="Bref résumé de l'article pour l'affichage en liste.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
