# Generated by Django 5.0.14 on 2026-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_pressarticle_content_en_pressarticle_content_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Si faux, la salle n'apparaîtra pas dans les listes publiques (utile pour modération)."),
        ),
    ]
