# Generated by Django 5.0.14 on 2026-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_alter_pressarticle_user_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_fr',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_nl',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
