# Generated by Django 5.0.14 on 2026-05-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_alter_type_type_alter_type_type_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows_genre', to='catalogue.type'),
        ),
    ]
