# Generated by Django 5.0.14 on 2026-05-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_show_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=60, null=True)),
                ('name_en', models.CharField(blank=True, max_length=60, null=True)),
                ('name_nl', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='catalogue.genre'),
        ),
    ]
