# Generated by Django 5.0.14 on 2026-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_genre_alter_show_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_fr',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_nl',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
