# Generated by Django 5.0.14 on 2026-05-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_alter_genre_name_en_alter_genre_name_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representationreservation',
            name='representation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='representation_reservations', to='catalogue.representation'),
        ),
    ]
